### ISSUE TITLE
AWS Credentials Expired During CDK Deployment

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/backend-infra-cdk#3]
# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15931997202](https://github.com/CloudSmith-Delivery-Troubleshooting/backend-infra-cdk/actions/runs/15931997202) |  ```p1-branch``` |  ```77a75472b62dc0d8e7c112551713ebe3fb19f068``` |
----
### Issue 1

**Problem**: The CDK Deploy step is failing because the AWS temporary security token has expired. The GitHub Actions workflow is using OIDC authentication with role assumption, but the token has a maximum duration (typically 1 hour) which was exceeded during the deployment process. The CDK deployment started at 17:12:32Z and failed at 18:12:25Z, which is almost exactly 1 hour later, confirming that the token expired during the deployment.

**File**: ```.github/workflows/deploy.yml```

**Error Log**:
```
Error: Could not load credentials from ChainableTemporaryCredentials2: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1: Could not load credentials from ChainableTemporaryCredentials2: The security token included in the request is expired
```

**Code snippet**:
```
- name: Configure AWS credentials\n        uses: aws-actions/configure-aws-credentials@v4\n        with:\n          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsRole\n          aws-region: ${{ env.AWS_REGION }}
```

**Solution Plan**:

1. Modify the AWS credential configuration in the GitHub workflow to include a token refresh mechanism: - Update the "Configure AWS credentials" step to include the `role-session-duration` parameter to request a longer session (up to the maximum allowed by the role, typically 12 hours) - Add a credential refresh step before the CDK Deploy step  Here\'s the updated code for the workflow file:
```yaml
                - name: Configure AWS credentials
                  uses: aws-actions/configure-aws-credentials@v4
                  with:
                    role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
                    aws-region: ${{ env.AWS_REGION }}
                    role-session-duration: 3600  # Request 1 hour session (in seconds)
```
2. Split the CDK deployment into smaller stacks if possible to reduce deployment time.
3. Add a credential refresh step before the CDK Deploy step:
```yaml
                - name: Refresh AWS credentials
                  uses: aws-actions/configure-aws-credentials@v4
                  with:
                    role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
                    aws-region: ${{ env.AWS_REGION }}
                    role-session-duration: 3600
```
4. Consider implementing a deployment strategy that can handle credential refreshes during long-running deployments: - Use CDK\'s `--no-rollback` option to prevent rollbacks on failure - Implement a retry mechanism for the deployment step - Consider using AWS CodePipeline for complex deployments that might exceed token lifetimes

----

# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15931997202](https://github.com/CloudSmith-Delivery-Troubleshooting/backend-infra-cdk/actions/runs/15931997202) |  ```p1-branch``` |  ```77a75472b62dc0d8e7c112551713ebe3fb19f068``` |
----
### Issue 2

**Problem**: The recent commit changed the container image from \'python:3.9-slim\' to \'myproject/web.server\', but there\'s no indication that this image exists in a public registry. The image might not be available, which could cause deployment issues, although this wasn\'t the immediate cause of the current failure.

**File**: ```lib/backend-infra-stack.ts```

**Error Log**:
```
N/A - This issue didn\'t cause the current failure but could cause future deployment failures
```

**Code snippet**:
```
taskImageOptions: {\n          image: ecs.ContainerImage.fromRegistry(\'myproject/web.server\'),\n          containerName: `${prefix}-backend-container`,\n          containerPort: 3000,\n          logDriver: ecs.LogDriver.awsLogs({\n            streamPrefix: \'ecs\',\n            logGroup: logGroup,\n          }),\n          entryPoint: [\'python\', \'-m\', \'http.server\', \'3000\'],\n        },
```

**Solution Plan**:

1. Verify if the \'myproject/web.server\' image exists in a public Docker registry (like Docker Hub)
2. If the image doesn\'t exist, either: - Create and push the image to a public registry - Use an existing public image - Push the image to the ECR repository that\'s being created in the stack
3. If using a private registry: - Update the code to use ECR repository:
```typescript
                   // Option 1: Use the ECR repository created in this stack
                   image: ecs.ContainerImage.fromEcrRepository(ecrRepository, \'latest\'),
                   
                   // Option 2: If using a pre-existing ECR repository
                   image: ecs.ContainerImage.fromEcrRepository(
                     ecr.Repository.fromRepositoryName(
                       this, 
                       `${prefix}-ExistingRepo`, 
                       \'myproject/web.server\'
                     ),
                     \'latest\'
                   ),
```
4. If the image should be public, ensure it\'s available in Docker Hub or another public registry
5. Consider adding repository credentials if needed:
```typescript
                   taskImageOptions: {
                     image: ecs.ContainerImage.fromRegistry(\'myproject/web.server\', {
                       credentials: secretsManager.Secret.fromSecretNameV2(
                         this,
                         `${prefix}-DockerHubCreds`,
                         \'docker-hub-credentials\'
                       )
                     }),
                     // other options...
                   }
```

----
